name: wheel
   
on:
     workflow_dispatch:
jobs:
      
  build_and_upload:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel 
    - name: Build 
      run: |
        python setup.py sdist bdist_wheel
    - name: finiding the wheel's version
      run: |
        output=$(python source/wheel_version.py)
        echo "::set-output name=version::$output"
      id: wheel_version_name
    - name: upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: wheel 
        path: dist/insightsprocessor-${{ steps.wheel_version_name.outputs.version }}-py3-none-any.whl

  checkout_and_push: 
    needs: build_and_upload

    runs-on: ubuntu-latest

    steps:

    - name: checkout to output
      uses: actions/checkout@v3
      with:
        repository: 'noakfir/output'
        token: ${{ secrets.PERSONAL_TOKEN}}
        persist-credentials: false 
        fetch-depth: 0
   
 
    - name: upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: wheel 
        path: local wheels
    
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: ~/aqouant-si-be/local_wheels
    
    - name: Display structure of downloaded files
      run: |
        ls -R
        echo "::set-output name=version::ls -R"
      working-directory: ~/aqouant-si-be/local_wheels
    
    - name: commit and push to output 
      run: |
        git config --local user.email "noa.kfir@aquant.io"
        git config --local user.name "noakfir"
        git fetch
        git status
        git add .
        git status
        git commit -m"try"
        git push 
